spring:
  application:
    name: b2c-member-service

  datasource:
      url: jdbc:mysql://106.14.177.29:3306/test
      username: root
      password: yuan
      driver-class-name: com.mysql.jdbc.Driver
      tomcat:
        max-active: 20
        max-idle: 8
        min-idle: 8
        initial-size: 10
      type: com.alibaba.druid.pool.DruidDataSource
server:
  port: 10100
eureka:
  client:
    serviceUrl:
      defaultZone: http://106.14.177.29:8761/eureka/

mybatis:
  type-aliases-package: com.b2c.tests
  mapper-locations: classpath:mapper/*.xml